apiVersion: v2
name: netobserv-flow
description: ElastiFlow NetObserv Flow Collector
type: application
version: 0.5.2
appVersion: 7.19.3
icon: https://artifacthub.io/image/a7c44004-9982-4ba1-a4c9-c626340d3d38@2x
sources:
  - https://github.com/elastiflow/helm-chart-netobserv
  - https://hub.docker.com/r/elastiflow/flowcollector/
maintainers:
  - name: ElastiFlow Engineering Team
    email: engineering@elastiflow.com
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/elastiflow/helm-chart-netobserv
keywords:
  - netflow
  - network
  - flow
  - observability
